### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by careguaro** [Netpeople2005/JangoMailBundle#1]
Buenas!!! 

Soy Carlos García, nuevo desarrollador de la oficina de Amplex de Chacao y estoy trabajando sobre un sistema de envío de comunicados utilizando este Bundle, para hacer tareas como envío de correos, obtener reportes, crear listas/grupos, entre otras cosas. Me ha surgido un problema con algunas secciones del mismo, por ejemplo: cuando intento cargar unas de las listas de la cuenta de JangoMail a través del template "miembros.html.twig" me salta un error que me dice que el método "getFlashes" no existe en el componente httpFoundation, de hecho me he ocupado de revisarlo y efectivamente no existe, supongo que esto se debe a que es un método creado por ustedes, de ser así me gustaría saber que hace exactamente el método en cuestión y si es posible que me lo hagan llegar porque veo que es usado en varías de las plantillas del entorno de prueba del bundle y asi me ahorro un tiempo valioso mas aún que estamos un poco justo con el tiempo de entrega del sistema.

Gracias,

Saludos.

**Comment by manuelj555** [comment]
Buenas, no es un método de nosotros, es un metodo desactualizado de las primeras versiones de symfony (2.0, 2.1).
